name: example-node-versions
on:
  workflow_dispatch:

jobs:
  show-default-node:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04-arm
          - ubuntu-24.04-arm
          - windows-11-arm
    runs-on: ${{ matrix.os }}
    steps:
      - run: node -v
      - run: npm -v
      - name: Show runner infos
        run: |
          node -p "'OS type:     ' + os.type()"
          node -p "'OS version:  ' + os.version()"
          node -p "'OS release:  ' + os.release()"
          node -p "'OS platform: ' + os.platform()"
          node -p "'OS arch:     ' + os.arch()"
          node -p "'OS machine:  ' + os.machine()"
          echo "OS cpus:"
          node -p "os.cpus()"

  show-nodes:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04-arm
          - ubuntu-24.04-arm
          - windows-11-arm
          - windows-2025
        node:
          - 20
          - 22
          - 24
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: node -v
      - run: npm -v
      - run: |
          node -p "'OS platform: ' + os.platform()"
          node -p "'OS arch:     ' + os.arch()"
          node -p "'OS machine:  ' + os.machine()"
          echo "OS cpus:"
          node -p "os.cpus()"
