name: example-ci-test
on:
  workflow_dispatch:

env:
  DEBUG: '@cypress/github-action'

jobs:

  pass-example:
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        id: cypress
        uses: ./
        with:
          working-directory: examples/basic
          spec: cypress/e2e/pass.cy.js

      - name: 'Print previous step outcome/conclusion'
        if: always()
        id: print
        run: |
            echo "outcome: ${{ steps.cypress.outcome }}"
            echo "conclusion: ${{ steps.cypress.conclusion }}"

  fail-example:
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        id: cypress
        uses: ./
        with:
          working-directory: examples/basic
          spec: cypress/e2e/fail.cy.js

      - name: 'Print previous step outcome/conclusion'
        if: always()
        id: print
        run: |
            echo "outcome: ${{ steps.cypress.outcome }}"
            echo "conclusion: ${{ steps.cypress.conclusion }}"
