name: example-edge
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

env:
  CYPRESS_CONNECT_RETRY_THRESHOLD: 20

jobs:
  tests:
    name: all os
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-2022, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress info and test
        uses: ./
        with:
          # just for full picture after installing Cypress
          # print information about detected browsers, etc
          # see https://on.cypress.io/command-line#cypress-info
          build: npm run info
          working-directory: examples/browser
          browser: edge
