name: example-basic
on:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  basic:
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Cypress tests
        uses: $/
        with:
          working-directory: examples/basic
          browser: firefox
