name: example-edge
# In the example jobs, the action is called with
# uses: ./
# which runs the action code from the current branch.
# If you copy this workflow to another repo, replace the line with
# uses: cypress-io/github-action@v6
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  edge:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Edge
        uses: ./
        with:
          # just for full picture after installing Cypress
          # print information about detected browsers, etc
          # see https://on.cypress.io/command-line#cypress-info
          build: npm run info
          working-directory: examples/browser
          browser: edge

  edge-stable:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Edge stable
        id: setup-edge
        # see https://github.com/browser-actions/setup-edge
        uses: browser-actions/setup-edge@v1
        with:
          edge-version: stable

      - name: Edge stable
        uses: ./
        with:
          working-directory: examples/browser
          browser: ${{ steps.setup-edge.outputs.edge-path }}
