name: example-node-versions
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  check-node-versions:
    strategy:
      fail-fast: false
      matrix:
        node:
          - 22
          - 24
          - 25
          - 26
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
      - run: node -v
      - run: npm -v
