name: example-custom-command
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

env:
  DEBUG: '@cypress/github-action,cypress:*'

jobs:
  start:
    # example where instead of forming the default "cypress run ..."
    # the user can specify their own command
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Custom tests 🧪
        uses: ./
        with:
          command: npm run custom-test
          working-directory: examples/custom-command

      - name: Show saved file 🖨
        run: cat examples/custom-command/results.json
