name: example-chrome
on:
  # push:
  #   branches:
  #     - 'master'
  # pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        chrome-version:
          - latest
          - stable
          # - beta
          # - dev
          # - canary
          - 137
          - 137.0.7151.70
    steps:
      - name: Checkout
        uses: actions/checkout@v4

        # https://github.com/browser-actions/setup-chrome
      - name: Install Chrome separately
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: ${{ matrix.chrome-version }}
          install-dependencies: true

      - name: Cypress
        uses: ./
        with:
          command: npx cypress info
          working-directory: examples/browser
