name: example-wait-on
# In the example jobs, the action is called with
# uses: ./
# which runs the action code from the current branch.
# If you copy this workflow to another repo, replace the line with
# uses: cypress-io/github-action@v7
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:
permissions:
  contents: read

jobs:

  wait-on-vite:
    runs-on: ubuntu-26.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Cypress tests
        uses: ./
        with:
          working-directory: examples/wait-on-vite
          start: npx vite --host
          wait-on: 'http://localhost:5173'

  wait-on-vite-https:
    runs-on: ubuntu-26.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Cypress tests
        uses: ./
        env:
          # the dev server uses a self-signed certificate
          NODE_TLS_REJECT_UNAUTHORIZED: '0'
        with:
          working-directory: examples/wait-on-vite
          config-file: cypress.config-https.js
          start: npm run dev:https -- --host
          wait-on: 'npx wait-on --timeout 60000 https://localhost:5174'
