name: example-component-test
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  cypress-run-ubuntu:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          working-directory: examples/component-tests
          component: true
          browser: firefox

  cypress-run-windows:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          working-directory: examples/component-tests
          component: true
          browser: firefox

  cypress-run-windows-debug:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          working-directory: examples/component-tests
          component: true
          browser: firefox
        env:
          DEBUG: '@cypress/github-action, cypress:*'
