name: example-firefox
# In the example jobs, the action is called with
# uses: ./
# which runs the action code from the current branch.
# If you copy this workflow to another repo, replace the line with
# uses: cypress-io/github-action@v6
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  firefox:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Firefox default
        uses: ./
        timeout-minutes: 3
        with:
          # let's show browser and system info
          build: npx cypress info
          working-directory: examples/browser
          browser: firefox # uses default Firefox version from runner image

      # report screenshot size and store the screenshots as test artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: screenshots-in-firefox
          path: examples/browser/cypress/screenshots

      - run: npx image-size cypress/screenshots/**/*.png
        working-directory: examples/browser

  firefox-latest:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Firefox latest
        id: setup-firefox
        # see https://github.com/browser-actions/setup-firefox
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: latest

      - name: Firefox latest
        uses: ./
        timeout-minutes: 3
        with:
          working-directory: examples/browser
          browser: ${{ steps.setup-firefox.outputs.firefox-path }}
