name: example-firefox
on:
  push:
    branches:
      - 'master'
  pull_request:
jobs:

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Cypress v9 and lower ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

  firefox:
    # should include Firefox browser install
    # https://github.com/actions/virtual-environments
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Firefox
        uses: ./
        timeout-minutes: 3
        with:
          # let's show browser and system info
          build: npx cypress info
          working-directory: examples/v9/firefox
          browser: firefox

      # report screenshot size and store the screenshots as test artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: screenshots-in-firefox-v9
          path: examples/v9/firefox/cypress/screenshots

      - run: npx image-size cypress/screenshots/**/*.png
        working-directory: examples/v9/firefox

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Cypress v10 and higher ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

  firefox-v10:
    # should include Firefox browser install
    # https://github.com/actions/virtual-environments
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Firefox
        uses: ./
        timeout-minutes: 3
        with:
          # let's show browser and system info
          build: npx cypress info
          working-directory: examples/v10/firefox
          browser: firefox

      # report screenshot size and store the screenshots as test artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: screenshots-in-firefox-v10
          path: examples/v10/firefox/cypress/screenshots

      - run: npx image-size cypress/screenshots/**/*.png
        working-directory: examples/v10/firefox
