name: example-node-versions
on:
  workflow_dispatch:

jobs:
  show-default-node:
    runs-on: windows-11-arm
    steps:
      - run: systeminfo
      - run: node -v
      - run: npm -v
  show-nodes:
    runs-on: windows-11-arm
    strategy:
      fail-fast: false
      matrix:
        node: [20, 22, 24]
    name: Cypress E2E on Node v${{ matrix.node }}
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: node -v
      - run: npm -v
