name: example-custom-command
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  start:
    # example where instead of forming the default "cypress run ..."
    # the user can specify their own command
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Custom tests 🧪
        uses: ./
        with:
          command-prefix: percy exec -- npx
          working-directory: examples/custom-command
          auto-cancel-after-failures: 5
          browser: none
          ci-build-id: 12345
          component: true
          config: baseUrl=http://localhost:3000
          config-file: missing.json
          env: MY_ENV_VAR=12345
          group: my-group
          headed: true
          parallel: true
          project: my-project
          quiet: true
          record: true
          spec: missing.cy.js
          tag: my-tag
