name: example-firefox
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  firefox:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Firefox
        uses: ./
        timeout-minutes: 10
        with:
          # let's show browser and system info
          build: npx cypress info
          working-directory: examples/browser
          browser: firefox

      - name: Firefox 2
        uses: ./
        with:
          working-directory: examples/browser
          browser: firefox

      - name: Firefox 3
        uses: ./
        with:
          working-directory: examples/browser
          browser: firefox

      - name: Firefox 4
        uses: ./
        with:
          working-directory: examples/browser
          browser: firefox

      - name: Firefox 5
        uses: ./
        with:
          working-directory: examples/browser
          browser: firefox
