name: example-node-versions
on:
  workflow_dispatch:

jobs:
  show-default-node:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-22.04
          - ubuntu-24.04-arm
          - ubuntu-22.04-arm
          - windows-2025
          - windows-2022
          - windows-2019
          - windows-11-arm
    runs-on: ${{ matrix.os }}
    steps:
      - run: node -v
      - run: npm -v
      - run: corepack -v
      - name: Show runner infos
        run: |
          node -p "'OS type:     ' + os.type()"
          node -p "'OS version:  ' + os.version()"
          node -p "'OS release:  ' + os.release()"
          node -p "'OS platform: ' + os.platform()"
          node -p "'OS arch:     ' + os.arch()"
          node -p "'OS machine:  ' + os.machine()"
          echo "OS cpus:"
          node -p "os.cpus()"
