name: example-yarn-classic
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  yarn-classic:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: rm /usr/local/bin/yarn
      - run: |
          npm install corepack@latest -g
          corepack enable yarn

      - name: Test with Yarn Classic
        run: yarn install --frozen-lockfile
        working-directory: examples/yarn-classic
