name: example-node-versions
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:

  node-run:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        node: [18, 20, 22, 23, 'lts/*']
    name: Node v${{ matrix.node }}
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: node -v
      - run: npm -v
  node-run-latest:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        node: [18, 20, 22, 23, 'lts/*']
    name: Node v${{ matrix.node }} check latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
      - run: node -v
      - run: npm -v
