name: example-debug

# This workflow demonstrates how to use the DEBUG environment variable to get debug output.
# See also https://github.com/cypress-io/github-action/blob/master/README.md#debugging and
# https://on.cypress.io/troubleshooting#Print-DEBUG-logs

# In the example jobs, the action is called with
# uses: ./
# which runs the action code from the current branch.
# If you copy this workflow to another repo, replace the above line with
# uses: cypress-io/github-action@v6

on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  npm:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress action debug logs
        uses: ./
        env:
          # This enables debug logging output for the action
          DEBUG: '@cypress/github-action'
        with:
          command-prefix: '--'
          browser: chrome
          working-directory: examples/basic

  pnpm:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress action debug logs
        uses: ./
        env:
          # This enables debug logging output for the action
          DEBUG: '@cypress/github-action'
        with:
          command-prefix: '--'
          browser: chrome
          working-directory: examples/basic-pnpm
  yarn-classic:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress action debug logs
        uses: ./
        env:
          # This enables debug logging output for the action
          DEBUG: '@cypress/github-action'
        with:
          command-prefix: '--'
          browser: chrome
          working-directory: examples/yarn-classic

  yarn-modern:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress action debug logs
        uses: ./
        env:
          # This enables debug logging output for the action
          DEBUG: '@cypress/github-action'
        with:
          command-prefix: '--'
          browser: chrome
          working-directory: examples/yarn-modern
