name: example-yarn-modern-pnp
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:

  yarn-modern-pnp:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

        # Corepack is experimental - see https://nodejs.org/docs/latest/api/corepack.html
        # To avoid Corepack issues with key integrity checks, we use the latest version
        # and install dependencies before using the action
      - name: Install latest Corepack
        run: npm install -g corepack@latest
      - run: corepack enable yarn
      - name: Install dependencies
        run: yarn install --immutable
        working-directory: examples/yarn-modern-pnp

      - name: Cypress run
        uses: ./
        with:
          working-directory: examples/yarn-modern-pnp
          install: false
          # Yarn PnP does not support npx, so we need to use yarn explicitly to run Cypress.
          command: yarn run --binaries-only cypress run
