name: example-docker

on:
  workflow_dispatch:

env:
  DEBUG: '@cypress/github-action'

# jobs:
  # cypress-run:
  #   runs-on: ubuntu-22.04
  #   # Cypress Docker image with Chrome v106
  #   # and Firefox v106 pre-installed
  #   container: cypress/browsers:node18.12.0-chrome106-ff106
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: cypress-io/github-action@v5
  #       with:
  #         browser: chrome
  #         working-directory: examples/basic

jobs:
  # e2e:
  #   name: End-to-end
  #   runs-on: ubuntu-latest
  #   container: cypress/included:10.11.0

  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v2

  #     - name: Cypress run
  #       uses: cypress-io/github-action@v4
  #       with:
  #         working-directory: examples/basic
  e2e:
    name: End-to-end
    runs-on: ubuntu-latest
    container: cypress/included:12.17.1

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - run: id
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          working-directory: examples/basic
