name: example-component-test
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run ct
        uses: cypress-io/github-action@v5
        with:
          working-directory: examples/component-tests
          component: true
      - name: Cypress run e2e
        uses: cypress-io/github-action@v5
        with:
          working-directory: examples/component-tests
