name: example-recording
#
# To set up this workflow to work with your own Cypress Cloud project
# refer to the README in the example directory examples/recording.
#
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

env:
  # Set up the Cypress Cloud project ID and record key as environment variables
  # If the Actions secret EXAMPLE_PROJECT_ID is not defined then
  # the projectId is taken from cypress.config.js.
  # If the Actions secret EXAMPLE_RECORDING_KEY is not defined then recording jobs are skipped.
  CYPRESS_PROJECT_ID: ${{ secrets.EXAMPLE_PROJECT_ID }}
  CYPRESS_RECORD_KEY: ${{ secrets.EXAMPLE_RECORDING_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  check-record-key:
    runs-on: ubuntu-24.04
    outputs:
      record-key-exists: ${{ steps.record-key-check.outputs.defined }}
    steps:
      - name: Check for record key
        id: record-key-check
        run: |
          if [ "${{ secrets.EXAMPLE_RECORDING_KEY }}" != '' ]; then
            echo "defined=true" >> $GITHUB_OUTPUT;
          else
            echo "defined=false" >> $GITHUB_OUTPUT;
          fi

  parallel:
    runs-on: ubuntu-24.04
    needs: [check-record-key]
    strategy:
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        chrome-version: [139, 140]
    if: needs.check-record-key.outputs.record-key-exists == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Chrome ${{ matrix.chrome-version }}
        id: setup-chrome
        uses: browser-actions/setup-chrome@v2 # https://github.com/browser-actions/setup-chrome
        timeout-minutes: 5
        with:
          chrome-version: ${{ matrix.chrome-version }}

      - name: Cypress tests
        uses: ./
        # let's give this action an ID so we can refer
        # to its output values later
        id: cypress
        with:
          working-directory: examples/recording
          build: npx cypress info
          record: true
          parallel: true
          group: Recording example
          tag: action
          browser: ${{ steps.setup-chrome.outputs.chrome-path }}
